feat: update recipe serializers
MoigeMatino/african-recipes-api pull request #41
Opened 2023-05-21 17:45 UTC by MoigeMatino

## Description

- Updates `RecipeCreateSerializer` and `RecipeSerializer`

## Reason for change

- To match new model structure.

## Checklist

- [ ] I have added/updated tests for this change (if applicable).
- [ ] I have updated the documentation (if applicable).
- [x] This PR doesn't contain any unrelated changes.

## References

- N/A

2023-05-25 04:04 UTC, lewis-munyi requested changes
The verb in the class and function/method names should come before the noun. i.e RecipeCreateSerializer should read CreateRecipeSerializer.

2023-05-25 05:06 UTC, MoigeMatino commented
> The verb in the class and function/method names should come before the noun. i.e RecipeCreateSerializer should read CreateRecipeSerializer.

My idea was that for easy readability we should place the entity name first. This is because with the many other serializers we'll create, we can easily identify them eg RecipeCreateSerializer, CommentCreateSerializer vs CreateRecipeSerializer, CreateCommentSerializer. That's why I opted for the convention to have the noun precede the verb. Thoughts?

2023-05-25 05:16 UTC, lewis-munyi commented
> > The verb in the class and function/method names should come before the noun. i.e RecipeCreateSerializer should read CreateRecipeSerializer.
> 
> My idea was that for easy readability we should place the entity name first. This is because with the many other serializers we'll create, we can easily identify them eg RecipeCreateSerializer, CommentCreateSerializer vs CreateRecipeSerializer, CreateCommentSerializer. That's why I opted for the convention to have the noun precede the verb. Thoughts?

That would've worked then but the files are split up now. Each file holds classes related to a particular model ie `serializers/recipes.py` will have all serializers relating to the `Recipe` model hence no need for the model name going first.

2023-05-31 19:29 UTC, lewis-munyi approved these changes

2023-05-31 19:29 UTC, merged